import type { Metadata } from 'next';
import './globals.css';
import ReduxProvider from '@/components/Providers/ReduxProvider';
import { ToasterProvider } from '@/components/Providers/ToasterProvider';
import AuthProvider from '@/components/Providers/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ReduxProvider>
            <ToasterProvider />
            {children}
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
